apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      hostPID: true

      tolerations:
        - operator: Exists

      containers:
        - name: node-exporter
          image: prom/node-exporter:latest
          args:
            - --path.rootfs=/host/root
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          volumeMounts:
            - name: root
              mountPath: /host/root
              readOnly: true

      volumes:
        - name: root
          hostPath:
            path: /
